### ISSUE TITLE
Add "getting started" instructions to the README

### ISSUE THREAD

**Issue by njbennett** [jaresty/liberating-structures#3]
I'm curious about trying this out but I'm not sure what I would need to do. Does it need to be hosted somewhere? Do I need to install the `slack` CLI?

**Comment by jaresty** [comment]
It's been a while since I deployed so I can't test-drive the instructions, but I added the two steps I remember. Can you give it a shot and let me know if you run into issues?

**Comment by jaresty** [comment]
I added a bit more information to try and clarify how to get started.
